#! python


def build(ctx):

    for s in 'maternal_involvement_personality','paternal_involvement_personality','parental_involvement_difference','parental_involvement_added_up':

        ctx(
            features='run_py_script',
            source='visual.py',
            target=ctx.path_to(ctx, 'OUT_FIGURES', 'figure_{}.jpeg'.format(s)),
            name='figure_{}'.format(s)
        )

