#! python


def build(ctx):

        ctx(
            features='run_py_script',
            source='regression.py',
            target=ctx.path_to(ctx, 'OUT_ANALYSIS', 'regression_result.tex'),
            name='regression_result.tex'
        )
